version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "schenectady-buses"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nzm4dmpok74k"
s3_prefix = "schenectady-buses"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
